server:
  port: 8082

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8088"




