server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: sanju
    password: sanju1234
    driver-class-name: com.mysql.jdbc.Driver
  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      base-path: /actuator
    exposure:
      include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
